# -*- coding: utf-8 -*-
"""01_simple_chat_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1po00kstar2iOMJuXMe27JUbP7rPt21dP

## TASK 1 — Salary Tax Calculator (Conditionals)
"""

salary = float(input("Enter your salary: "))

if salary < 30000:
    tax_rate = 0.05
elif salary <= 70000:
    tax_rate = 0.15
else:
    tax_rate = 0.25

tax = salary * tax_rate
final_salary = salary - tax

print("Tax Rate:", tax_rate * 100, "%")
print("Tax Amount:", tax)
print("Salary After Tax:", final_salary)

"""## Explanation

This program uses conditional statements (if–elif–else):
| Condition      | Tax |
| -------------- | --- |
| salary < 30000 | 5%  |
| 30k–70k        | 15% |
| >70k           | 25% |

The program:

1. Takes salary input
2. Chooses correct tax rate
3. Calculates tax and final salary

## TASK 2 — List → Dictionary (Data Structures)
"""

words = ["apple", "banana", "kiwi", "cherry", "mango"]

word_length_dict = {}

for word in words:
    word_length_dict[word] = len(word)

print(word_length_dict)

"""## Explanation

This task uses:

- List → stores multiple values
- Dictionary → stores key:value pairs

We loop through each word and store:

| Word   | Length |
| ------ | ------ |
| apple  | 5      |
| banana | 6      |

Dictionary format:
```
{"apple":5, "banana":6}
```

## TASK 3 — Chat System Using OOP

Now we combine classes + objects (real-world simulation).

## Step 1: Create User Class
"""

class User:
    def __init__(self, name):
        self.name = name

"""👉 Represents a chat user.

## Step 2: Create Message Class
"""

class Message:
    def __init__(self, sender, text):
        self.sender = sender
        self.text = text

"""👉 Represents each message sent.

## Step 3: Create ChatRoom Class
"""

class ChatRoom:
    def __init__(self):
        self.users = []
        self.messages = []

    def join(self, user):
        self.users.append(user)
        print(user.name, "joined the chat")

    def leave(self, user):
        self.users.remove(user)
        print(user.name, "left the chat")

    def send_message(self, message):
        self.messages.append(message)
        print(message.sender.name + ":", message.text)

    def show_history(self):
        print("\nChat History:")
        for msg in self.messages:
            print(msg.sender.name + ":", msg.text)

"""## Step 4: Use the Chat System"""

# Create chat room
room = ChatRoom()

# Create users
user1 = User("Ali")
user2 = User("Sara")

# Users join chat
room.join(user1)
room.join(user2)

# Send messages
room.send_message(Message(user1, "Hello everyone!"))
room.send_message(Message(user2, "Hi Ali!"))

# Show chat history
room.show_history()

# User leaves
room.leave(user2)

"""## OOP Concept Explanation

| Concept       | Meaning                             |
| ------------- | ----------------------------------- |
| Class         | Blueprint (User, Message, ChatRoom) |
| Object        | Real instance (Ali, Sara)           |
| Method        | Functions inside class              |
| Encapsulation | Data stored inside objects          |

This simulates a real chat app structure.

## Full Coding of this Task
"""

# Step 1: Create User Class

class User:
    def __init__(self, name):
        self.name = name
# Represents a chat user.

# Step 2: Create Message Class

class Message:
    def __init__(self, sender, text):
        self.sender = sender
        self.text = text

# Represents each message sent.

# Step 3: Create ChatRoom Class

class ChatRoom:
    def __init__(self):
        self.users = []
        self.messages = []

    def join(self, user):
        self.users.append(user)
        print(user.name, "joined the chat")

    def leave(self, user):
        self.users.remove(user)
        print(user.name, "left the chat")

    def send_message(self, message):
        self.messages.append(message)
        print(message.sender.name + ":", message.text)

    def show_history(self):
        print("\nChat History:")
        for msg in self.messages:
            print(msg.sender.name + ":", msg.text)


# Step 4: Use the Chat System
# Create chat room
room = ChatRoom()

# Create users
user1 = User("Ali")
user2 = User("Sara")

# Users join chat
room.join(user1)
room.join(user2)

# Send messages
room.send_message(Message(user1, "Hello everyone!"))
room.send_message(Message(user2, "Hi Ali!"))

# Show chat history
room.show_history()

# User leaves
room.leave(user2)