# -*- coding: utf-8 -*-
"""Price_Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srkRYZ5807Zj_HJZCGUlk9n7ftMaKnyW

## House Price Prediction using Linear Regression
### Objective

In this exercise, we build and evaluate a Machine Learning model using the House Price Prediction dataset. The workflow includes:

1. Train-Test Split
2. Model Training
3. Model Prediction
4. Model Evaluation
5. Interpretation of Results

## Step 1: Import Required Libraries
"""

# Import libraries
import pandas as pd
import numpy as np

# For data preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Machine Learning model
from sklearn.linear_model import LinearRegression

# Evaluation metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""## Explanation
- pandas is used for handling datasets.
- numpy is used for numerical operations.
- train_test_split divides the dataset into training and testing sets.
- LabelEncoder converts categorical values into numeric form.
- LinearRegression is the machine learning algorithm.
- Evaluation metrics help measure model performance.

## Step 2: Load the Dataset
"""

from google.colab import files
uploaded = files.upload()

# Load dataset
file_path = 'HousePricePrediction.csv'
df = pd.read_csv(file_path)

# Display first 5 rows
print(df.head())

"""## Explanation

This step loads the dataset into a DataFrame and displays the first 5 rows.

## Step 3: Check Dataset Information
"""

# Dataset information
print(df.info())

# Check missing values
print(df.isnull().sum())

"""## Explanation
- info() shows column names and data types.
- isnull().sum() checks missing values in each column.

## Step 4: Handle Categorical Columns
"""

# Convert categorical columns into numerical values
label_encoder = LabelEncoder()

for column in df.select_dtypes(include=['object']).columns:
    df[column] = label_encoder.fit_transform(df[column].astype(str))

print(df.head())

"""## Explanation

Machine Learning models require numeric data. Therefore, categorical columns such as MSZoning, LotConfig, and Exterior1st are converted into numeric values.

## Step 5: Handle Missing Values
"""

# Fill missing values with column mean
for column in df.columns:
    df[column] = df[column].fillna(df[column].mean())

# Verify missing values
print(df.isnull().sum())

"""## Explanation

Missing values are replaced with the mean value of each column.

## Step 6: Define Features and Target Variable
"""

# Features (Independent Variables)
X = df.drop('SalePrice', axis=1)

# Target Variable (Dependent Variable)
y = df['SalePrice']

"""## Explanation
- X contains all input features.
- y contains the target variable SalePrice.

## Step 7: Train-Test Split
"""

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print('Training Data Shape:', X_train.shape)
print('Testing Data Shape:', X_test.shape)

"""## Explanation
- 80% of the data is used for training.
- 20% of the data is used for testing.
- random_state=42 ensures reproducibility.

## Step 8: Train the Linear Regression Model
"""

# Create Linear Regression model
model = LinearRegression()
model

# Train the model
model.fit(X_train, y_train)

print('Model training completed successfully.')

"""## Explanation

The Linear Regression model learns patterns from the training dataset.

## Step 9: Make Predictions
"""

# Predict house prices on test data
y_pred = model.predict(X_test)

# Display first 5 predictions
print('Predicted Values:')
print(y_pred[:5])

"""## Explanation

The trained model predicts house prices using the testing dataset.

## Step 10: Evaluate the Model
"""

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# Print results
print('Mean Absolute Error (MAE):', mae)
print('Mean Squared Error (MSE):', mse)
print('Root Mean Squared Error (RMSE):', rmse)
print('R² Score:', r2)

# Step Compare Actual vs Predicted (first 10 rows)
comparison = pd.DataFrame({'Actual': y_test[:10], 'Predicted': y_pred[:10]})
print("\n  Actual vs Predicted House Prices (Sample):")
print(comparison)

"""## Explanation of Metrics
1. Mean Absolute Error (MAE)

MAE measures the average prediction error. Lower MAE means better model performance.

2. Mean Squared Error (MSE)

MSE measures squared prediction errors. Large errors receive higher penalties.

3. Root Mean Squared Error (RMSE)

RMSE is the square root of MSE. It represents prediction error in the same unit as house prices.

4. R² Score

R² score measures how well the model explains the data.

- Closer to 1 = Better model
- Closer to 0 = Poor model

## Step 11: Interpretation of Results
Interpretation

The Linear Regression model achieved a good R² score, which indicates that the model can explain a significant portion of the variation in house prices.

The MAE and RMSE values show that the prediction error is reasonable, but there is still room for improvement.

The model performance can be improved by:

1. Feature Engineering
2. Removing Outliers
3. Using Advanced Algorithms such as:
 - Random Forest Regressor
 - Decision Tree Regressor
 - XGBoost Regressor
4. Hyperparameter Tuning
5. Data Scaling and Normalization

Overall, the Linear Regression model provides satisfactory results for basic house price prediction.

## Graphical Representation of Results
Actual Prices vs Predicted Prices Graph
"""

import matplotlib.pyplot as plt

# Plot Actual vs Predicted values
plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred)

# Perfect prediction line
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')

# Labels and title
plt.xlabel('Actual House Prices')
plt.ylabel('Predicted House Prices')
plt.title('Actual vs Predicted House Prices')

plt.show()

import matplotlib.pyplot as plt

plt.scatter(y_test[:50], y_pred[:50], color='blue', label='Predicted vs Actual')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', label='Perfect Fit')
plt.xlabel("Actual Sale Price")
plt.ylabel("Predicted Sale Price")
plt.title("Actual vs Predicted House Prices")
plt.legend()
plt.show()

"""## Explanation of the Graph
- Each dot represents one house prediction.
- The red dashed line represents perfect predictions.
- If points are close to the red line, the model predictions are accurate.
- Points far from the line represent prediction errors.

If most points are clustered near the line, it means the model is performing well.
"""